---
- name: 配置nginx源
  copy: src=nginx.repo dest=/etc/yum.repos.d/

- name: 安装nginx
  yum: name=nginx state=present 

- name: 配置nginx.conf
  template: src=nginx.conf dest=/etc/nginx/nginx.conf
  notify: restart nginx

- name: 配置default.conf
  template: src=default.conf.j2 dest=/etc/nginx/conf.d/default.conf
  notify: restart nginx

- name: 启动nginx
  service: name=nginx state=started enabled=yes
