---
- name: Install common nginx php nodejs mysql redis
  hosts: all
  #hosts: 192.168.200.219
  remote_user: root
  roles:
    - common
          #- nginx
          #- php-fpm
          #- nodejs
          #- mysql
          #- redis
