---
- name: restart mysqld
  service: name=mysqld state=restarted

- name: Find temporary password
  shell: "echo `grep 'temporary.*root@localhost' /var/log/mysqld.log | sed 's/.*root@localhost: //'`"
  register: mysql_root_password_temp

- name: Set new password from temporary password
  shell: 'mysql -e "SET PASSWORD = PASSWORD(''{{ root_password }}'');" --connect-expired-password -uroot -p"{{ mysql_root_password_temp.stdout }}"'

- name: 创建mysql用户
  mysql_user:
    login_user: 'root'
    login_host: 'localhost'
    login_password: "{{ root_password }}"
    name: "{{ mysqluser }}"
    password: "{{ mysqlpasswd }}"
    priv: '*.*:ALL'
    host: '%'
    state: present
